name: CI/CD Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy to VPS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Debug IP
      run: | 
        echo "IP is: ${{ secrets.SERVERIP }}"

    - name: Setup SSH access
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRIKEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVERIP }} >> ~/.ssh/known_hosts

    - name: Clean remote directory
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.SERVERUSER }}@${{ secrets.SERVERIP }} << 'EOF'
        mkdir -p ~/my-website
        cd ~/my-website
        rm -rf *
        EOF
        
    - name: Copy files to VPS
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SERVERIP }}
        username: ${{ secrets.SERVERUSER }}
        key: ${{ secrets.PRIKEY }}
        source: "."
        target: "~/my-website"

    - name: Build and run Docker container on VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVERIP }}
        username: ${{ secrets.SERVERUSER}}
        key: ${{ secrets.PRIKEY }}
        script: |
          cd ~/my-website
          docker stop my-website || true
          docker rm my-website || true
          docker build -t my-website .
          docker run -d --name my-website -p 80:3000 my-website
