name: CI/CD Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy to VPS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug IP
      run: |
        echo "IP is: ${{ secrets.SERVERIP }}"

    - name: Setup SSH access using ssh-agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.PRIKEY }}

    - name: Clean remote directory
      run: |
        ssh -T -i ~/.ssh/id_rsa ${{ secrets.SERVERUSER }}@${{ secrets.SERVERIP }} << 'EOF'
          mkdir -p ~/my-website
          cd ~/my-website
          rm -rf *
        EOF

    - name: Create Dockerfile on VPS
      run: |
        ssh -T -i ~/.ssh/id_rsa ${{ secrets.SERVERUSER }}@${{ secrets.SERVERIP }} << 'EOF'
          cat << 'EOF2' > ~/my-website/Dockerfile
          # Use Node base image
          FROM node:18

          # Set working directory
          WORKDIR /app

          # Copy package files
          COPY package*.json ./

          # Install dependencies
          RUN npm install

          # Copy the rest of the code
          COPY . .

          # Expose the port
          EXPOSE 3000

          # Start the app
          CMD ["npm", "start"]
          EOF2
        EOF

    - name: Copy files to VPS
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SERVERIP }}
        username: ${{ secrets.SERVERUSER }}
        key: ${{ secrets.PRIKEY }}
        source: "."
        target: "~/my-website"

    - name: Build and run Docker container on VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVERIP }}
        username: ${{ secrets.SERVERUSER}}
        key: ${{ secrets.PRIKEY }}
        script: |
          cd ~/my-website
          sudo docker stop my-website || true
          sudo docker rm my-website || true
          sudo docker build -t my-website .
          sudo docker run -d --name my-website -p 80:3000 my-website
